site_name: Jackipedia
site_url: https://wiki.jackshudson.com

theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: green
  features:
    - navigation.instant
    - navigation.sections
    - search.suggest
    - search.highlight

plugins:
  - search
  - roamlinks
  - awesome-pages
  - section-index

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - footnotes
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Category Theory: 'Mathematics/Category Theory/Category Theory.md'
